version: '3.8'

services:

  master:
    build:
       context: ./master
       dockerfile: Dockerfile
    environment:
      - ENV=docker
    ports:
      - "9090:9090"

  secondary.1:
    build:
       context: ./secondary
       dockerfile: Dockerfile
    ports:
      - "9001:9000"

  secondary.2:
    build:
       context: ./secondary
       dockerfile: Dockerfile
    ports:
      - "9002:9000"

  secondary.delay:
    build:
      context: ./secondary
      dockerfile: Dockerfile
    command: ["python", "-m", "app", "--host=0.0.0.0", "--port=9000", "--delay=10"]
    ports:
      - "9003:9000"